### ISSUE TITLE
Reporting: Scenarios

### ISSUE THREAD

**Issue by magnusandy** [magnusandy/ModelingJohnesDisease#24]
5) Scenarios
a) Scenario Descriptions: Description of one or more “what if” scenarios with the model to
explore different possible situations.
1) Describe the a “baseline” scenario, and the motivation for choosing it
2) Alternative situations examined. These situations could reflect, for example
a) The results of implementing different policies
b) Different possible external conditions.
c) Understanding behavior
b) Findings from scenario runs
1) Findings related to the domain area (from insights from the runs)
2) Findings related to the model
3) Other findings

**Comment by add118** [comment]
Parameters we are able to change for scenario building:
- InitialPopulation
- InitialInfectedPercentage
- InitialSubClinicalPercentage
- InitialClinicalPercentage
- ClinicalPrevalenceModifier 
  - SubClinicalPrevalenceModifier is static at a baseline of 1, ClinicalPrevalenceMultiplier just needs to be greater
- MeanClinicalRemovalDuration 
  - Currently 2 months, but we can see if lowering this has an effect on the number of infections during this removal duration, as the cow is shedding the entire time. Remember to set the simulation seed to "Fixed" in the Randomness window of the SensitivityAnalysis scenario.
- FrequencyOfInfectionContact
- GrazingCalfIntensityOfPrevalenceModifer
  - WeaningCalfIntensityOfPrevalenceModifer should stay at 1 since they are susceptible at normal levels.
- ClinicalMultiplier
  - (Multiplier used to increase the spread of the disease when the cows is in the clinical state.) Currently has the value 4. Is this quite static? How did we decide on this one?
- FecalTestReturnDelay (Default 2 weeks)
- BloodTestReturnDelay (Default 2 weeks)
- PositiveCowRemovalDelay (Default 2 weeks)

These next 6 can technically be changed, but it may not be necessary to change them as they have reasonable levels.
- FecalTestInfectedSensitivity
- FecalTestSubClinicalSensitivity
- FecalTestClinicalSensitivity
- BloodTestInfectedSensitivity
- BloodTestSubClinicalSensitivity
- BloodTestClinicalSensitivity

**Comment by add118** [comment]
Goals of Scenarios:
- To measure the effectiveness of the individual testing types
- To measure the effectiveness of the testing types in combination
- To determine the mean time required to remove the disease from a herd of different sizes and infection prevalence
- To identify an ideal stopping point for testing when the confidence level of a risk free herd has reached a limit (we have yet to define a limit)

Some general ideas:
- [x] High population (1000) 
- [x] Low population (100)
- [ ] High Initial Infection (High Initial Infection Percentages)
- [ ] Low Initial Infection (Low Initial Infection Percentages)
- [x] Fast removal after positive test result (Lower PositiveCowRemovalDelay parameters)
- [x] Slow removal after positive test result (Higher PositiveCowRemovalDelay parameters)
- [ ] Hyper realistic without testing (Get very accurate population and density parameters from a real life situation and play around with sensitivity analysis. No testing)
- [ ] Hyper realistic with testing (Get very accurate population and density parameters from a real life situation and play around with sensitivity analysis. Yes testing)
- [ ] Very High infective contact (FrequencyOfInfectionContact > 7.1) 
- [ ] Very Low infective contact (0 < FrequencyOfInfectionContact < 7.1) (Essentially just MotherToCalfContact)

**Comment by magnusandy** [comment]
We should keep the restrict the scenarios to only a few (maybe 5) Cheryl suggested several already, we should have a baseline scenario for the disease that is, one without testing, we should also do one with each test as well as combined. Because the focus of this project and of the scenarios as you stated is on testing and removal/treatment of cows, our scenarios should focus around testing parameters.  Scenarios probably shouldn't ask what if questions about disease transmission or change values like invective rate because they do not lead to valuable answers. 
I like the idea of fast/slow removal times as should make a large difference to how effective the tests are working (if you test but take 6 months to remove whats the point?) Calibration and sensitivity testing will mostly focus on the infection model as especially the environmental prevalence rate is largely an unknown quantity that we can try to better tune/understand through calibration and sensitivity analysis.

**Comment by add118** [comment]
This was just to give us ideas. I was listing all of the parameters that are changeable so that we can just reference this Issue. As for the list of scenarios, we can make as many as we want but we are only reporting on a few (the ones Cheryl talked about). Just let me know which ones aren't even worth considering and I'll remove them from the list.

**Comment by add118** [comment]
Complete.
