### ISSUE TITLE
Graphs and outputs

### ISSUE THREAD

**Issue by magnusandy** [magnusandy/ModelingJohnesDisease#30]
Some suggestions by Osgood,
- [x] histogram of time between infection and disgnosis (or perhaps state which they were caught in or both)
- [x] age of infection
- [x] current Age vs current state scatterplot

**Comment by add118** [comment]
More additional graphs that Cheryl might find uses for.

- [x] Cows Removed through positive test results / total diseased cows

- [x] Cows missed by testing / total diseased cows

- [ ] Scatterplot of Calf State (Weaning of Grazing) VS. Disease state of cow that infected them

- [ ] Graph of changing probabiliy of positive test results over time. P(Blood+ OR Fecal+) is highest at the beginning when there are more cows in clinical state. Because clinical cows have a higher chance of being test positive, they are removed more frequently, which then reduces the Overall Probability of any individual cow being test positive in the next batch of testing. This can be graphed, and from this we can get the expected value of the number of test positive cows every year.

**Comment by magnusandy** [comment]
we can't really graph which state the infecting cow is in because environmental prevalence is an aggregate value, we could look to see what state the mother is in, clinical or subclinical but I don't really see how helpful that would be.

I don't understand the last one.
