### ISSUE TITLE
Review Charts during next meeting

### ISSUE THREAD

**Issue by add118** [magnusandy/ModelingJohnesDisease#41]
I left TODO's in descriptions for some charts because I think we need to revisit them and decide which ones to keep and which ones to change/delete.

**Comment by magnusandy** [comment]
As we discussed with Cheryl the Critical graphs are:
- WeightedPrevalence ( Showing prevalence, weighted prevalence and overall prevalence)
- infectionFromSourceTimePlot
- infectionSpreadOverTime (showing cows by infection state)

These should be front and center, the rest should be made smaller and moved out of the way as they are more for sanity checking and data display rather than analysis

I think that the testing ones could also be highlighted, but not as much as the top 3

**Comment by add118** [comment]
She likes the current charts.
